/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBtn: typeof import('./../components/el/btn.vue')['default']
    ElBtnToggle: typeof import('./../components/el/btnToggle.vue')['default']
    ElCheckbox: typeof import('./../components/el/checkbox.vue')['default']
    ElDivider: typeof import('./../components/el/divider.vue')['default']
    ElImg: typeof import('./../components/el/img.vue')['default']
    ElInput: typeof import('./../components/el/input.vue')['default']
    ElInputBox: typeof import('./../components/el/inputBox.vue')['default']
    ElRadio: typeof import('./../components/el/radio.vue')['default']
    ElSelect: typeof import('./../components/el/select.vue')['default']
    ElSkill: typeof import('./../components/el/skill.vue')['default']
    ElSvgIcon: typeof import('./../components/el/svgIcon.vue')['default']
    LayoutArticle: typeof import('./../components/layout/article.vue')['default']
    LayoutBlog: typeof import('./../components/layout/blog.vue')['default']
    LayoutLayoutest: typeof import('./../components/layout/layoutest.vue')['default']
    MoleSkillBox: typeof import('./../components/mole/skillBox.vue')['default']
    MoleWorkExperience: typeof import('./../components/mole/workExperience.vue')['default']
    OrgaResumeHeader: typeof import('./../components/orga/resume-header.vue')['default']
    OrgaSectionBlock: typeof import('./../components/orga/sectionBlock.vue')['default']
    TemplateResume: typeof import('./../components/template/resume.vue')['default']
  }
}
